-- créer les tables

BEGIN;

DROP TABLE IF EXISTS "coffee_characteristic", "coffee", "characteristic", "country";

CREATE TABLE "country" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT UNIQUE NOT NULL

    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "characteristic" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT UNIQUE NOT NULL

    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "coffee" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "reference" CHAR(9) UNIQUE NOT NULL,
    "price" DECIMAL NOT NULL,
    "country_id" INT NOT NULL REFERENCES "country"("id"),
    "availability" BOOLEAN NOT NULL DEFAULT false,

    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "coffee_characteristic"( 
  "coffee_id" INT NOT NULL REFERENCES "coffee"("id"), 
  "characteristic_id" INT NOT NULL REFERENCES "characteristic"("id"), 
  PRIMARY KEY ("coffee_id", "characteristic_id") 
);

COMMIT;